### ISSUE TITLE
Display project logo + name on the same line

### ISSUE THREAD

**Issue by PhilH** [Tribute-coop/server#24]
**Current presentation**
![image](https://user-images.githubusercontent.com/53337/43785258-33906f00-9a66-11e8-8ad2-49ef561bb0bd.png)

**Suggested improvement**
![image](https://user-images.githubusercontent.com/53337/43785431-8e12a5ec-9a66-11e8-8e62-73218b6e7c13.png)

**Comment by biodigitals** [comment]
we have to deal with the long name case.

the sidebar is getting large with names like "my wondefull new project"

how should we handle this ?

by truncating : "my wonderfull ..."

by putting onto multiple lines ?

"my wonderful
new project"

by restricting the lengthavailable for the project name ?

**Comment by PhilH** [comment]
NB: Same problem might occur with the current layout (logo and text and two different lines)  :)

I suggest that we just truncate, maybe with a tool tip showing the whole name when hovering over the area for more than a second. 

I assume that in most cases, owners will prefer to shorten the project name so that it stay readable on one line.

Ultimately there are other ways to deal with it, but they are uselessly complicated at this stage.
