### ISSUE TITLE
Can't add an initiative

### ISSUE THREAD

**Issue by PhilH** [Tribute-coop/server#71]
Messages in French:
![image](https://user-images.githubusercontent.com/53337/46143165-72e09980-c259-11e8-8614-10ce203bfade.png)

I tried with initiative names without a space char, doesn't solve the issue.

**Comment by biodigitals** [comment]
looks like it's not the latest vesrion.
Were you using content server ? If so .. please close the issue

**Comment by PhilH** [comment]
It is content server. I'm closing the issue then, but we need another system to track content and staging issues outside of github.
